#!/usr/bin/env bash
# Displays numbers 1–20 with special messages for 4, 9, 17

i=1
while [ "$i" -le 20 ]
do
    if [ "$i" -eq 4 ]
    then
        echo "4"
        echo "bad luck from China"
    elif [ "$i" -eq 9 ]
    then
        echo "9"
        echo "bad luck from Japan"
    elif [ "$i" -eq 17 ]
    then
        echo "17"
        echo "bad luck from Italy"
    else
        echo "$i"
    fi
    i=$((i + 1))
done
