#!/usr/bin/env bash
# This script manages manage_my_process (start/stop/restart)

PIDFILE="/var/run/my_process.pid"

start() {
    ./manage_my_process &
    echo $! > "$PIDFILE"
    echo "manage_my_process started"
}

stop() {
    kill "$(cat "$PIDFILE")"
    rm -f "$PIDFILE"
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) restart ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
